### ISSUE TITLE
咨询两个问题

### ISSUE THREAD

**Issue by hz-kelpie** [chriskaliX/Hades#2]
1. 不知道有没有遗漏，我看网络行为收集都是基于进程FORK/EXEC的，如果进程在运行过程中新增的网络行为是不是检测不到？
2. 维护进程树的考虑主要是啥？

**Comment by chriskaliX** [comment]
对于问题1，我之前理解有点偏差了。我记得写在了 socket.go，方法依然是轮询

**Comment by hz-kelpie** [comment]
进程关联网络行为这个地方我也在找好方法，/proc/{pid}/net/这个目录下的tcp/udp/unix这些文件里的内容其实和/proc/net/下的是一样的，是整台机器的所有连接，所以你获取到的inode是整台机器的所有连接，如果在前端机，每产生一个进程就遍历一次，性能会爆炸的

**Comment by chriskaliX** [comment]
:-) 嗯嗯，这个方法不错的样子，我研究一下。所以目前的方式都是定时扫一下，每隔一段时间扫描一次。

**Comment by chriskaliX** [comment]
后期改进，有问题随时留言，感谢交流~
