### ISSUE TITLE
同为HIDS产品研发，认识一下

### ISSUE THREAD

**Issue by cfc4n** [chriskaliX/Hades#3]
你好，我是CFC4N，在美团负责HIDS等安全产品研发，也是美团HIDS那篇文章的作者，看到你这里在从事HIDS相关研发，方便认识一下吗？
找不到你联系方式，可以email里交流微信ID哈。我的邮箱：Y2ZjNG4uY3NAZ21haWwuY29t  
😊

**Comment by chriskaliX** [comment]
非常荣幸！！！立马添加，感谢大佬

**Comment by chriskaliX** [comment]
已发送
