### ISSUE TITLE
有没有交流群

### ISSUE THREAD

**Issue by ruoniao** [chriskaliX/Hades#5]
有没有交流群？小白一个，希望技术探讨类的主题还是即时通讯比较方便。

**Comment by chriskaliX** [comment]
可以的，我新建一个，更新在 README 里面

**Comment by muse117** [comment]
怎么不建个微信群呢。。感觉飞书不是很常用。。

**Comment by chriskaliX** [comment]
> 怎么不建个微信群呢。。感觉飞书不是很常用。。

OK的，我建一个，更新在 README

**Comment by chriskaliX** [comment]
@muse117 已更新
