### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by poppyred** [chriskaliX/Hades#52]
**Describe the bug**
特定系统下有乱码
```json
{"starttime":79570157046599,"cgroupid":4294968467,"pns":0,"type":700,"pid":31760,"tid":31760,"uid":0,"gid":0,"ppid":0,"pgid":0,"sessionid":0,"comm":"cat","pcomm":"","nodename":"","retval":0,"exe_hash":"-3","username":"root","timestamp":1660032991,"exe":"-1","syscall":"execve","ppid_argv":"-3","pgid_argv":"-3","pod_name":"-3","cwd":"-1","tty_name":"��(\u0004�����sC�����","stdin":"-1","stdout":"-1","dport":0,"dip":"-1","family":0,"socket_pid":0,"socket_argv":"-3","pid_tree":"4294967295.��\u0007\u0002������\u0007\u0002���","argv":"cat /sys/class/dmi/id/product_serial","priv_esca":0,"ssh_connection":"-1","ld_preload":"-1"}
```

**Environment**
- OS Information: Linux 5.4.0-122-generic #138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**

```
cd Hades/plugin/driver/eBPF/
go run .
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11489072/183603256-4b91c1d2-84a1-41cd-bb23-18225b3a59d9.png)

**Comment by chriskaliX** [comment]
感谢提交，我看看

**Comment by chriskaliX** [comment]
![image](https://user-images.githubusercontent.com/46471110/183614854-4af5b62e-0634-4037-b337-55cb21d2f665.png)方便的话可以加一下这个群，这样定位更快一点～

**Comment by chriskaliX** [comment]
Closed due to run driver cross different kernel version
