### ISSUE TITLE
[BUG] kernel 4.19 not work

### ISSUE THREAD

**Issue by wcc526** [chriskaliX/Hades#72]
sys_enter_execveat: load program: invalid argument: unrecognized bpf_ld_imm64 insn , couldn't load eBPF programs 

on kernel 4.19

**Comment by chriskaliX** [comment]
issue received. Would you please provide more information about the issue.
I test in alinos 8.2, which is kernel 4.18 it works

**Comment by chriskaliX** [comment]
I guess it's anolis 7.9? I'll test into this

**Comment by chriskaliX** [comment]
found the kernel version, I'll test this

**Comment by chriskaliX** [comment]
issue confirmed, global const related, I'm looking into this

**Comment by chriskaliX** [comment]
another llvm related issue, working on this

**Comment by chriskaliX** [comment]
There are several issues in kernel 4.19...delay to this weekend

**Comment by chriskaliX** [comment]
https://github.com/gojue/ecapture/pull/40
related-issue

**Comment by chriskaliX** [comment]
Issue is tackled, push tomorrow

**Comment by chriskaliX** [comment]
patched
https://github.com/chriskaliX/Hades/pull/73
