### ISSUE TITLE
[BUG]pod_name is null

### ISSUE THREAD

**Issue by wcc526** [chriskaliX/Hades#75]
[BUG]pod_name is null

`
{"starttime":1686193822,"cgroupid":1,"pns":0,"pid":64825,"tid":64825,"uid":0,"gid":0,"ppid":0,"pgid":0,"sessionid":4294937234,"comm":"modprobe","pcomm":"","nodename":"","retval":0,"exe_hash":"-1","username":"root","exe":"-1","syscall":"execve","ppid_argv":"-1","pgid_argv":"-1","pod_name":"-1","cwd":"-1","tty_name":"-1","stdin":"-1","stdout":"-1","dport":0,"dip":"0.0.0.0","sport":0,"sip":"0.0.0.0","family":0,"socket_pid":0,"socket_argv":"-1","pid_tree":"","argv":"/sbin/modprobe ip_tables","priv_esca":0,"ssh_connection":"-1","ld_preload":"-1"}
`

**Comment by chriskaliX** [comment]
issue received, I'll look into this case this weekend.

**Comment by chriskaliX** [comment]
Can not reproduce the issue, since we get the from the `/proc/<pid>/environ`, would you please start a process inside the pod, like "nc -lvvp xxxx", and execute `cat  /proc/<pid>/environ` to see whether it contains POD_NAME or MY_POD_NAME
