### ISSUE TITLE
dns data is wrong

### ISSUE THREAD

**Issue by wcc526** [chriskaliX/Hades#76]
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	AnolisOS
Description:	Anolis OS release 8.8
Release:	8.8
Codename:	n/a

`
{"starttime":1686893499,"cgroupid":1,"pns":1442590160,"pid":12152,"tid":12122,"uid":0,"gid":0,"ppid":0,"pgid":0,"sessionid":0,"comm":"consul-1.1.1-1","pcomm":"","nodename":"","retval":90,"exe_hash":"-1","username":"root","exe":"-1","syscall":"udp_recvmsg","ppid_argv":"-1","pgid_argv":"-1","pod_name":"-1","opcode":7,"rcode":10,"qtype":0,"atype":0,"dns_data":"M�\u0004AP\u0013#\u0017�//TV$����1)\n�p�f)�М%�\u001c��B� I��r�S�8��L7O�P��\u001d\u0007��F\u0014��g7�|\u0008��)�89��","sip":"10.197.192.44","sport":8301,"dip":"0.0.0.0","dport":0}
`

**Comment by chriskaliX** [comment]
![image](https://github.com/chriskaliX/Hades/assets/46471110/d2eb45fc-0696-4b13-8bcb-5d7315071f59)
Can not reproduce the issue, in anolis 8.8

**Comment by chriskaliX** [comment]
reopen this if problem reproduced
