### ISSUE TITLE
[BUG] kernel 6.6.30 does not work

### ISSUE THREAD

**Issue by ringbuffer0** [chriskaliX/Hades#82]
**Describe the bug**
It looks like it won't work on my linux kernel,and It always reports this  error:"load program: invalid argument: invalid func unknown#195896080 (63 line(s) omitted)"

1011 map[level:error msg:error:program kprobe_udp_recvmsg: load program: invalid argument: invalid func unknown#195896080 (63 line(s) omitted) , couldn't load eBPF programs, cs:&{map[.bss:Array(keySize=4, valueSize=8196, maxEntries=1, flags=0) bufs:PerCPUArray(keySize=4, valueSize=32768, maxEntries=4, flags=0) bufs_off:PerCPUArray(keySize=4, valueSize=4, maxEntries=3, flags=0) cgroup_id_filter:Hash(keySize=8, valueSize=4, maxEntries=512, flags=0) config_map:Hash(keySize=4, valueSize=8, maxEntries=512, flags=0) connect_cache:LRUHash(keySize=8, valueSize=12, maxEntries=4096, flags=0) deny_filter:LRUHash(keySize=8, valueSize=4, maxEntries=20, flags=0) exec_events:PerfEventArray(keySize=4, valueSize=4, maxEntries=8, flags=0) file_events:PerfEventArray(keySize=4, valueSize=4, maxEntries=8, flags=0) inner_filter:LRUHash(keySize=8, valueSize=16, maxEntries=20, flags=0) net_events:PerfEventArray(keySize=4, valueSize=4, maxEntries=8, flags=0) path_filter:Array(keySize=4, valueSize=128, maxEntries=3, flags=0) pid_filter:Hash(keySize=4, valueSize=4, maxEntries=512, flags=0) pns_filter:Hash(keySize=4, valueSize=4, maxEntries=512, flags=0) syscall_buffer_cache:Hash(keySize=8, valueSize=8196, maxEntries=512, flags=0) udpmsg:LRUHash(keySize=8, valueSize=24, maxEntries=4096, flags=0) uid_filter:Hash(keySize=4, valueSize=4, maxEntries=512, flags=0)] map[kprobe_security_socket_bind:0xc0004fc360 kprobe_udp_recvmsg:0xc0004fc1b0 kretprobe_udp_recvmsg:0xc0004fc3f0 sys_enter_connect:0xc0004fc630 sys_enter_execve:0xc0004fc480 sys_enter_execveat:0xc0004fc510 sys_enter_memfd_create:0xc0004fc750 sys_enter_prctl:0xc0004fc120 sys_enter_ptrace:0xc0004fc6c0 sys_exit_connect:0xc0004fc2d0 sys_exit_execve:0xc0004fc090 sys_exit_execveat:0xc0004fc5a0] 0xc000240370 LittleEndian} source:edriver/main.go:26 timestamp:1732776830]

**Environment**
- OS Information: `uname -r` 6.6.30-5.tl4.x86_64

**To Reproduce**
1. Run 'make core; ./edriver --debug'
2. See error

**Expected behavior**

**Screenshots**
![20241128150413](https://github.com/user-attachments/assets/37bf19dd-bd4c-4578-a3e2-1230da55cde6)

**Additional context**

**Comment by chriskaliX** [comment]
Yeah... I encountered this problem few month ago. It seems Hades is not working over kernel 6.x, I'll look into the issue this weekend, thanks for reporting.

**Comment by chriskaliX** [comment]
issue fixed. close
